DATASETS:
  dataset_root: "data/downloaded_datasets"
  datasets:
    #example:
    example: "/path/to/your/dataset/example.jsonl"

    recommendation: "data/downloaded_datasets/vcb_bench/text_instruction_follow/chinese/recommendation/recommendation.jsonl"
    rewriting: "data/downloaded_datasets/vcb_bench/text_instruction_follow/chinese/rewriting/rewriting.jsonl"
    creation: "data/downloaded_datasets/vcb_bench/text_instruction_follow/chinese/creation/creation.jsonl"
    safety: "data/downloaded_datasets/vcb_bench/text_instruction_follow/chinese/safety/safety.jsonl"
    continuation: "data/downloaded_datasets/vcb_bench/text_instruction_follow/chinese/continuation/continuation.jsonl"
    empathy: "data/downloaded_datasets/vcb_bench/text_instruction_follow/chinese/empathy/empathy.jsonl"
    simulation: "data/downloaded_datasets/vcb_bench/text_instruction_follow/chinese/simulation/simulation.jsonl"
    
    pacing_control: "data/downloaded_datasets/vcb_bench/speech_instruction_follow/chinese/pacing_control/pacing_control.jsonl"
    volume_control: "data/downloaded_datasets/vcb_bench/speech_instruction_follow/chinese/volume_control/volume_control.jsonl"
    emotional_control: "data/downloaded_datasets/vcb_bench/speech_instruction_follow/chinese/emotional_control/emotional_control.jsonl" 
    language_control: "data/downloaded_datasets/vcb_bench/speech_instruction_follow/chinese/language_control/language_control.jsonl"
    style_control: "data/downloaded_datasets/vcb_bench/speech_instruction_follow/chinese/style_control/style_control.jsonl"
    non_verbal_vocalization: "data/downloaded_datasets/vcb_bench/speech_instruction_follow/chinese/non_verbal_vocalization/non_verbal_vocalization.jsonl"

    recommendation_en: "data/downloaded_datasets/vcb_bench/text_instruction_follow/english/recommendation_en/recommendation_en.jsonl"
    rewriting_en: "data/downloaded_datasets/vcb_bench/text_instruction_follow/english/rewriting_en/rewriting_en.jsonl"
    creation_en: "data/downloaded_datasets/vcb_bench/text_instruction_follow/english/creation_en/creation_en.jsonl"
    safety_en: "data/downloaded_datasets/vcb_bench/text_instruction_follow/english/safety_en/safety_en.jsonl"
    continuation_en: "data/downloaded_datasets/vcb_bench/text_instruction_follow/english/continuation_en/continuation_en.jsonl"
    empathy_en: "data/downloaded_datasets/vcb_bench/text_instruction_follow/english/empathy_en/empathy_en.jsonl"
    simulation_en: "data/downloaded_datasets/vcb_bench/text_instruction_follow/english/simulation_en/simulation_en.jsonl"

    pacing_control_en: "data/downloaded_datasets/vcb_bench/speech_instruction_follow/english/pacing_control_en/pacing_control_en.jsonl"
    volume_control_en: "data/downloaded_datasets/vcb_bench/speech_instruction_follow/english/volume_control_en/volume_control_en.jsonl"
    emotional_control_en: "data/downloaded_datasets/vcb_bench/speech_instruction_follow/english/emotional_control_en/emotional_control_en.jsonl"
    language_control_en: "data/downloaded_datasets/vcb_bench/speech_instruction_follow/english/language_control_en/language_control_en.jsonl"
    style_control_en: "data/downloaded_datasets/vcb_bench/speech_instruction_follow/english/style_control_en/style_control_en.jsonl"
    non_verbal_vocalization_en: "data/downloaded_datasets/vcb_bench/speech_instruction_follow/english/non_verbal_vocalization_en/non_verbal_vocalization_en.jsonl"

    accent: "data/downloaded_datasets/vcb_bench/real_scenario/speaker_variations/accent/accent.jsonl"
    accent_cmp: "data/downloaded_datasets/vcb_bench/real_scenario/speaker_variations/accent_cmp/accent_cmp.jsonl"
    age: "data/downloaded_datasets/vcb_bench/real_scenario/speaker_variations/age/age.jsonl"
    age_cmp: "data/downloaded_datasets/vcb_bench/real_scenario/speaker_variations/age_cmp/age_cmp.jsonl"
    speed: "data/downloaded_datasets/vcb_bench/real_scenario/speaker_variations/speed/speed.jsonl"
    speed_cmp: "data/downloaded_datasets/vcb_bench/real_scenario/speaker_variations/speed_cmp/speed_cmp.jsonl"
    vocal_noise: "data/downloaded_datasets/vcb_bench/real_scenario/environmental_variations/vocal_noise/vocal_noise.jsonl"
    vocal_noise_cmp: "data/downloaded_datasets/vcb_bench/real_scenario/environmental_variations/vocal_noise_cmp/vocal_noise_cmp.jsonl"
    non_vocal_noise: "data/downloaded_datasets/vcb_bench/real_scenario/environmental_variations/non_vocal_noise/non_vocal_noise.jsonl"
    non_vocal_noise_cmp: "data/downloaded_datasets/vcb_bench/real_scenario/environmental_variations/non_vocal_noise_cmp/non_vocal_noise_cmp.jsonl"
    unstable_signal: "data/downloaded_datasets/vcb_bench/real_scenario/environmental_variations/unstable_signal/unstable_signal.jsonl"
    unstable_signal_cmp: "data/downloaded_datasets/vcb_bench/real_scenario/environmental_variations/unstable_signal_cmp/unstable_signal_cmp.jsonl"
    volume: "data/downloaded_datasets/vcb_bench/real_scenario/speaker_variations/volume/volume.jsonl"
    volume_cmp: "data/downloaded_datasets/vcb_bench/real_scenario/speaker_variations/volume_cmp/volume_cmp.jsonl"
    fillers: "data/downloaded_datasets/vcb_bench/real_scenario/content_variations/fillers/fillers.jsonl"
    fillers_cmp: "data/downloaded_datasets/vcb_bench/real_scenario/content_variations/fillers_cmp/fillers_cmp.jsonl"
    repetition: "data/downloaded_datasets/vcb_bench/real_scenario/content_variations/repetition/repetition.jsonl"
    repetition_cmp: "data/downloaded_datasets/vcb_bench/real_scenario/content_variations/repetition_cmp/repetition_cmp.jsonl"
    mispronunciation: "data/downloaded_datasets/vcb_bench/real_scenario/content_variations/mispronunciation/mispronunciation.jsonl"
    mispronunciation_cmp: "data/downloaded_datasets/vcb_bench/real_scenario/content_variations/mispronunciation_cmp/mispronunciation_cmp.jsonl"
    grammatical_error: "data/downloaded_datasets/vcb_bench/real_scenario/content_variations/grammatical_error/grammatical_error.jsonl"
    grammatical_error_cmp: "data/downloaded_datasets/vcb_bench/real_scenario/content_variations/grammatical_error_cmp/grammatical_error_cmp.jsonl"
    topic_shift: "data/downloaded_datasets/vcb_bench/real_scenario/content_variations/topic_shift/topic_shift.jsonl"
    topic_shift_cmp: "data/downloaded_datasets/vcb_bench/real_scenario/content_variations/topic_shift_cmp/topic_shift_cmp.jsonl"
    code_switching: "data/downloaded_datasets/vcb_bench/real_scenario/content_variations/code_switching/code_switching.jsonl"
    code_switching_cmp: "data/downloaded_datasets/vcb_bench/real_scenario/content_variations/code_switching_cmp/code_switching_cmp.jsonl"
    casual_talk: "data/downloaded_datasets/vcb_bench/real_scenario/content_variations/casual_talk/casual_talk.jsonl"
    casual_talk_cmp: "data/downloaded_datasets/vcb_bench/real_scenario/content_variations/casual_talk_cmp/casual_talk_cmp.jsonl"

    general_knowledge: "data/downloaded_datasets/vcb_bench/general_knowledge/general_knowledge.jsonl"
    basic_math: "data/downloaded_datasets/vcb_bench/mathematical_logic/basic_math/basic_math.jsonl"
    math: "data/downloaded_datasets/vcb_bench/mathematical_logic/math/math.jsonl"
    logical_reasoning: "data/downloaded_datasets/vcb_bench/mathematical_logic/logical_reasoning/logical_reasoning.jsonl"

    story_continue: "data/downloaded_datasets/vcb_bench/pretrain_evaluation/story_continue/story_continue.jsonl"

    backtracking: "data/downloaded_datasets/vcb_bench/multi_turn_dialog/backtracking/backtracking.jsonl"
    progression: "data/downloaded_datasets/vcb_bench/multi_turn_dialog/progression/progression.jsonl"
    transition: "data/downloaded_datasets/vcb_bench/multi_turn_dialog/transition/transition.jsonl"

    discourse_comprehension: "data/downloaded_datasets/vcb_bench/discourse_comprehension/discourse_comprehension.jsonl"
